/** Adapter id lists for admin / docs — keep in sync with runner.ts registrations. */

export const ALL_ADAPTER_IDS = [
  "ra_chi",
  "ra_la",
  "ra_sf",
  "eventbrite",
  "eventbrite_chi",
  "eventbrite_la",
  "19hz",
  "19hz_chi",
  "19hz_la",
  "funcheap",
  "luma",
  "luma_chi",
  "luma_la",
  "ticketmaster",
  "ticketmaster_chi",
  "ticketmaster_la",
  "comedy_venue",
  "comedy_venue_chi",
  "comedy_venue_la",
  "stage_venue",
  "stage_venue_chi",
  "stage_venue_la",
  "music_venue",
  "music_venue_chi",
  "music_venue_la",
  "recurring",
  "movies_tms",
  "partiful",
  "newsletter",
  "instagram",
  "youtube",
  "openmic_agg",
  "indie_theater",
  "food",
  "food_deals",
  "activities",
  "theater",
  "new_restaurants",
  "do312",
  "dola",
  "chicago_cheap",
  "music_festival",
] as const;

export const PHASE1_ADAPTER_IDS = [
  "19hz",
  "19hz_chi",
  "19hz_la",
  "funcheap",
  "luma",
  "luma_chi",
  "luma_la",
  "ticketmaster",
  "ticketmaster_chi",
  "ticketmaster_la",
  "comedy_venue",
  "comedy_venue_chi",
  "comedy_venue_la",
  "stage_venue",
  "stage_venue_chi",
  "stage_venue_la",
  "music_venue",
  "music_venue_chi",
  "music_venue_la",
  "recurring",
  "do312",
  "dola",
  "chicago_cheap",
  "ra_chi",
  "ra_la",
  "ra_sf",
  "eventbrite",
  "eventbrite_chi",
  "eventbrite_la",
  "music_festival",
  // Lightweight curated rows — posters + HH / theater inventory without waiting for daily.
  "food_deals",
  "activities",
  "theater",
] as const;
