import { config } from "dotenv";
import { and, eq } from "drizzle-orm";
import { resolve } from "node:path";
import { db } from "./index.js";
import { recurringShows, userProfiles, users } from "./schema.js";

config({ path: resolve(process.cwd(), "../../.env") });

const DEMO_USER_ID = "00000000-0000-4000-8000-000000000001";

type RecurringSeedRow = {
  name: string;
  venueName: string;
  neighborhood: string;
  address: string;
  weekday: number;
  nthWeekday: number | null;
  hour: number;
  minute: number;
  priceHint: string;
  /** Interest category stored in comedy_subtype column (comedy.* or music.*). */
  comedySubtype: string;
  sourceUrl: string;
  trustWeight: number;
  lat: number;
  lng: number;
  city: string;
};

async function seed() {
  await db
    .insert(users)
    .values({
      id: DEMO_USER_ID,
      email: "you@bored.local",
      displayName: "You",
    })
    .onConflictDoNothing();

  await db
    .insert(userProfiles)
    .values({
      userId: DEMO_USER_ID,
      interests: [
        { category: "music.electronic", weight: 0.9 },
        { category: "comedy.underground", weight: 0.85 },
        { category: "comedy.club", weight: 0.7 },
        { category: "tech", weight: 0.6 },
        { category: "movies.arthouse", weight: 0.75 },
        { category: "food", weight: 0.5 },
        { category: "free", weight: 0.4 },
      ],
      neighborhoods: ["Mission", "North Beach", "SOMA"],
      budgetMax: 45,
      budgetTier: 2,
      budgetEnabled: false,
      preferFree: false,
      nightsOut: true,
      radiusMiles: 12,
      lat: 37.7749,
      lng: -122.4194,
      onboardingComplete: false,
    })
    .onConflictDoUpdate({
      target: userProfiles.userId,
      set: {
        interests: [
          { category: "music.electronic", weight: 0.9 },
          { category: "comedy.underground", weight: 0.85 },
          { category: "comedy.club", weight: 0.7 },
          { category: "tech", weight: 0.6 },
          { category: "movies.arthouse", weight: 0.75 },
          { category: "food", weight: 0.5 },
          { category: "free", weight: 0.4 },
        ],
      },
    });

  const comedySeed: RecurringSeedRow[] = [
    {
      name: "Coit Comedy",
      venueName: "Columbus Cafe (basement speakeasy)",
      neighborhood: "North Beach",
      address: "562 Green St, San Francisco, CA",
      weekday: 4,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$12–15 + 1 drink min",
      comedySubtype: "comedy.underground",
      sourceUrl: "https://www.coitcomedy.com/",
      trustWeight: 0.95,
      lat: 37.7995,
      lng: -122.4079,
      city: "sf",
    },
    {
      name: "Clement St Comedy",
      venueName: "Neck of the Woods",
      neighborhood: "Richmond",
      address: "406 Clement St, San Francisco, CA",
      weekday: 4,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "Free–$12",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://www.neckofthewoodssf.com/calendar/",
      trustWeight: 0.8,
      lat: 37.7829,
      lng: -122.4625,
      city: "sf",
    },
    {
      name: "Live at Deluxe",
      venueName: "Club Deluxe",
      neighborhood: "Haight",
      address: "1511 Haight St, San Francisco, CA",
      weekday: 1,
      nthWeekday: 3,
      hour: 21,
      minute: 0,
      priceHint: "Free",
      comedySubtype: "comedy.showcase",
      sourceUrl: "https://www.sfstandup.com/stagetime/",
      trustWeight: 0.75,
      lat: 37.7697,
      lng: -122.4469,
      city: "sf",
    },
    {
      name: "Hayes Valley Comedy Night",
      venueName: "The Function SF",
      neighborhood: "Hayes Valley",
      address: "1414 Market St, San Francisco, CA",
      weekday: 0,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "Free w/ RSVP · $20–25 door",
      comedySubtype: "comedy.showcase",
      sourceUrl: "https://www.thefunctionsf.com/",
      trustWeight: 0.9,
      lat: 37.7754,
      lng: -122.4178,
      city: "sf",
    },
    {
      name: "Golden Gate Comedy Night",
      venueName: "The Function SF",
      neighborhood: "Hayes Valley",
      address: "1414 Market St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "$20–25",
      comedySubtype: "comedy.club",
      sourceUrl: "https://www.thefunctionsf.com/",
      trustWeight: 0.9,
      lat: 37.7754,
      lng: -122.4178,
      city: "sf",
    },
    {
      name: "Laugh Lab",
      venueName: "The Function SF",
      neighborhood: "Hayes Valley",
      address: "1414 Market St, San Francisco, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "$20 door",
      comedySubtype: "comedy.underground",
      sourceUrl: "https://www.thefunctionsf.com/",
      trustWeight: 0.85,
      lat: 37.7754,
      lng: -122.4178,
      city: "sf",
    },
    {
      name: "Mabuhay Gardens Comedy",
      venueName: "Mabuhay Gardens",
      neighborhood: "North Beach",
      address: "443 Broadway, San Francisco, CA",
      weekday: 4,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "$15–25",
      comedySubtype: "comedy.underground",
      sourceUrl: "https://themab.org/",
      trustWeight: 0.85,
      lat: 37.7979,
      lng: -122.4055,
      city: "sf",
    },
    {
      name: "Open Mic Comedy",
      venueName: "Question Mark Tavern",
      neighborhood: "Mission",
      address: "San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Free / PWYC",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://www.sfbarguide.com/event-type/comedy-sf",
      trustWeight: 0.7,
      lat: 37.7599,
      lng: -122.4148,
      city: "sf",
    },
    {
      name: "Zanies Open Mic",
      venueName: "Zanies Comedy Club",
      neighborhood: "Old Town",
      address: "1548 N Wells St, Chicago, IL",
      weekday: 1,
      nthWeekday: null,
      hour: 19,
      minute: 30,
      priceHint: "$5–10",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://chicago.zanies.com/calendar/",
      trustWeight: 0.9,
      lat: 41.9097,
      lng: -87.6344,
      city: "chicago",
    },
    {
      name: "Comedy Bar Open Mic",
      venueName: "The Comedy Bar",
      neighborhood: "River West",
      address: "1460 N Milwaukee Ave, Chicago, IL",
      weekday: 3,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Free–$5",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://thecomedybar.com/shows/",
      trustWeight: 0.85,
      lat: 41.909,
      lng: -87.6745,
      city: "chicago",
    },
    {
      name: "Laugh Factory All-Stars",
      venueName: "Laugh Factory Chicago",
      neighborhood: "Lakeview",
      address: "3175 N Broadway, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$20–35",
      comedySubtype: "comedy.club",
      sourceUrl: "https://www.laughfactory.com/clubs/chicago",
      trustWeight: 0.9,
      lat: 41.9398,
      lng: -87.6447,
      city: "chicago",
    },
    {
      name: "Second City e.t.c.",
      venueName: "Second City",
      neighborhood: "Old Town",
      address: "230 W North Ave, Chicago, IL",
      weekday: 6,
      nthWeekday: null,
      hour: 19,
      minute: 30,
      priceHint: "$25–45",
      comedySubtype: "comedy.showcase",
      sourceUrl: "https://www.secondcity.com/shows/chicago/",
      trustWeight: 0.95,
      lat: 41.9115,
      lng: -87.6355,
      city: "chicago",
    },
    {
      name: "Lincoln Lodge",
      venueName: "Lincoln Lodge",
      neighborhood: "Bucktown",
      address: "2040 N Milwaukee Ave, Chicago, IL",
      weekday: 4,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$10–15",
      comedySubtype: "comedy.showcase",
      sourceUrl: "https://lincolnlodge.com/",
      trustWeight: 0.8,
      lat: 41.9178,
      lng: -87.6776,
      city: "chicago",
    },
    {
      name: "iO Improv Jam",
      venueName: "iO Theater",
      neighborhood: "River North",
      address: "1501 N Kingsbury St, Chicago, IL",
      weekday: 2,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$14",
      comedySubtype: "comedy.underground",
      sourceUrl: "https://ioimprov.com/chicago/shows/",
      trustWeight: 0.85,
      lat: 41.9084,
      lng: -87.6528,
      city: "chicago",
    },
    {
      name: "Annoyance Saturday",
      venueName: "Annoyance Theatre",
      neighborhood: "Lakeview",
      address: "851 W Belmont Ave, Chicago, IL",
      weekday: 6,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "$15–20",
      comedySubtype: "comedy.underground",
      sourceUrl: "https://theannoyance.com/shows/",
      trustWeight: 0.75,
      lat: 41.9398,
      lng: -87.6533,
      city: "chicago",
    },
    {
      name: "Chicago Improv weekend",
      venueName: "Chicago Improv",
      neighborhood: "Schaumburg",
      address: "5 Woodfield Mall, Schaumburg, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "$25–45",
      comedySubtype: "comedy.club",
      sourceUrl: "https://improv.com/chicago/calendar/",
      trustWeight: 0.9,
      lat: 42.0464,
      lng: -88.0373,
      city: "chicago",
    },
    {
      name: "Comedy Store showcase",
      venueName: "The Comedy Store",
      neighborhood: "Hollywood",
      address: "8433 W Sunset Blvd, Los Angeles, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$25–45",
      comedySubtype: "comedy.club",
      sourceUrl: "https://www.thecomedystore.com/calendar/",
      trustWeight: 0.95,
      lat: 34.0952,
      lng: -118.3739,
      city: "la",
    },
    {
      name: "Comedy Store Potluck",
      venueName: "The Comedy Store (Original Room)",
      neighborhood: "Hollywood",
      address: "8433 W Sunset Blvd, Los Angeles, CA",
      weekday: 0,
      nthWeekday: null,
      hour: 18,
      minute: 0,
      priceHint: "Free entry · patio sign-up 4–5p",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://www.thecomedystore.com/calendar/room/the-original-room",
      trustWeight: 0.95,
      lat: 34.0952,
      lng: -118.3739,
      city: "la",
    },
    {
      name: "Set of the Night",
      venueName: "The Comedy Store (Belly Room)",
      neighborhood: "Hollywood",
      address: "8433 W Sunset Blvd, Los Angeles, CA",
      weekday: 0,
      nthWeekday: null,
      hour: 22,
      minute: 30,
      priceHint: "Lotto · 1 drink min",
      comedySubtype: "comedy.underground",
      sourceUrl: "https://www.thecomedystore.com/calendar/",
      trustWeight: 0.9,
      lat: 34.0952,
      lng: -118.3739,
      city: "la",
    },
    {
      name: "Laugh Factory Hollywood",
      venueName: "Laugh Factory",
      neighborhood: "Hollywood",
      address: "8001 Sunset Blvd, Los Angeles, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 19,
      minute: 30,
      priceHint: "$20–35",
      comedySubtype: "comedy.club",
      sourceUrl: "https://www.laughfactory.com/hollywood",
      trustWeight: 0.9,
      lat: 34.0983,
      lng: -118.3647,
      city: "la",
    },
    {
      name: "Hollywood Improv weekend",
      venueName: "Hollywood Improv",
      neighborhood: "Hollywood",
      address: "8162 Melrose Ave, Los Angeles, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$25–40",
      comedySubtype: "comedy.club",
      sourceUrl: "https://improv.com/hollywood/",
      trustWeight: 0.9,
      lat: 34.0835,
      lng: -118.3735,
      city: "la",
    },
    {
      name: "Dynasty Typewriter",
      venueName: "Dynasty Typewriter",
      neighborhood: "Westlake",
      address: "2511 Wilshire Blvd, Los Angeles, CA",
      weekday: 4,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$15–25",
      comedySubtype: "comedy.underground",
      sourceUrl: "https://www.dynastytypewriter.com/",
      trustWeight: 0.85,
      lat: 34.0578,
      lng: -118.2765,
      city: "la",
    },
    {
      name: "UCB Sunset",
      venueName: "Upright Citizens Brigade",
      neighborhood: "Hollywood",
      address: "5919 Franklin Ave, Los Angeles, CA",
      weekday: 3,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$12–20",
      comedySubtype: "comedy.showcase",
      sourceUrl: "https://ucbcomedy.com/",
      trustWeight: 0.85,
      lat: 34.1054,
      lng: -118.3162,
      city: "la",
    },
    {
      name: "Largo at the Coronet",
      venueName: "Largo",
      neighborhood: "Hollywood",
      address: "366 N La Cienega Blvd, Los Angeles, CA",
      weekday: 2,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$20–35",
      comedySubtype: "comedy.showcase",
      sourceUrl: "https://largo-la.com/",
      trustWeight: 0.9,
      lat: 34.0778,
      lng: -118.3765,
      city: "la",
    },
    {
      name: "Flappers Comedy Club",
      venueName: "Flappers Comedy Club",
      neighborhood: "Burbank",
      address: "102 E Magnolia Blvd, Burbank, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 19,
      minute: 30,
      priceHint: "$15–25",
      comedySubtype: "comedy.club",
      sourceUrl: "https://www.flapperscomedy.com/",
      trustWeight: 0.8,
      lat: 34.1802,
      lng: -118.3117,
      city: "la",
    },
    {
      name: "Tuesday Night Comedy",
      venueName: "142 Throckmorton Theatre",
      neighborhood: "Mill Valley",
      address: "142 Throckmorton Ave, Mill Valley, CA",
      weekday: 2,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "$25–35",
      comedySubtype: "comedy.club",
      sourceUrl: "https://www.throckmortontheatre.org/",
      trustWeight: 0.9,
      lat: 37.906,
      lng: -122.545,
      city: "marin",
    },
    {
      name: "Tuesday Night Comedy",
      venueName: "The BreakRoom",
      neighborhood: "Downtown Berkeley",
      address: "2021 Shattuck Ave, Berkeley, CA",
      weekday: 2,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Free–$10",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://www.eventbrite.com/e/tuesday-night-comedy-at-the-breakroom-tickets-1805504274889",
      trustWeight: 0.8,
      lat: 37.8715,
      lng: -122.2687,
      city: "berkeley",
    },
    {
      name: "Storking Comedy Open Mic",
      venueName: "Stork Club",
      neighborhood: "Uptown Oakland",
      address: "2330 Telegraph Ave, Oakland, CA",
      weekday: 4,
      nthWeekday: null,
      hour: 18,
      minute: 30,
      priceHint: "Free–$5",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://thestorkcluboakland.com/",
      trustWeight: 0.85,
      lat: 37.8136,
      lng: -122.2682,
      city: "oakland",
    },
    {
      name: "Stay Gold Open Mic",
      venueName: "Stay Gold Deli",
      neighborhood: "West Oakland",
      address: "2635 San Pablo Ave, Oakland, CA",
      weekday: 1,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "Free",
      comedySubtype: "comedy.open_mic",
      sourceUrl: "https://www.instagram.com/staygoldoakland/",
      trustWeight: 0.75,
      lat: 37.8189,
      lng: -122.2728,
      city: "oakland",
    },
    {
      name: "Saturday Night Comedy",
      venueName: "Fireside Lounge",
      neighborhood: "Alameda",
      address: "1453 Webster St, Alameda, CA",
      weekday: 6,
      nthWeekday: 2,
      hour: 20,
      minute: 0,
      priceHint: "$15–20",
      comedySubtype: "comedy.showcase",
      sourceUrl: "https://www.alamedacomedy.com/",
      trustWeight: 0.85,
      lat: 37.7725,
      lng: -122.2765,
      city: "alameda",
    },
  ];

  /** Local jazz / live-music residencies — not Ticketmaster headliners. */
  const jazzSeed: RecurringSeedRow[] = [
    {
      name: "Live jazz at Mr. Tipple's",
      venueName: "Mr. Tipple's Jazz Club",
      neighborhood: "Mid-Market",
      address: "39 Fell St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 18,
      minute: 0,
      priceHint: "Cover varies · cocktails",
      comedySubtype: "music.jazz",
      sourceUrl: "https://mrtipplessf.com/home/",
      trustWeight: 0.95,
      lat: 37.7762,
      lng: -122.4185,
      city: "sf",
    },
    {
      name: "Saturday jazz at Mr. Tipple's",
      venueName: "Mr. Tipple's Jazz Club",
      neighborhood: "Mid-Market",
      address: "39 Fell St, San Francisco, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 18,
      minute: 0,
      priceHint: "Cover varies · cocktails",
      comedySubtype: "music.jazz",
      sourceUrl: "https://mrtipplessf.com/home/",
      trustWeight: 0.95,
      lat: 37.7762,
      lng: -122.4185,
      city: "sf",
    },
    {
      name: "Weeknight jazz at Mr. Tipple's",
      venueName: "Mr. Tipple's Jazz Club",
      neighborhood: "Mid-Market",
      address: "39 Fell St, San Francisco, CA",
      weekday: 3,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "Cover varies · cocktails",
      comedySubtype: "music.jazz",
      sourceUrl: "https://mrtipplessf.com/home/",
      trustWeight: 0.9,
      lat: 37.7762,
      lng: -122.4185,
      city: "sf",
    },
    {
      name: "Jazz supper club at Black Cat",
      venueName: "Black Cat",
      neighborhood: "Tenderloin",
      address: "400 Eddy St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Ticketed · dinner optional",
      comedySubtype: "music.jazz",
      sourceUrl: "https://blackcatsf.com/",
      trustWeight: 0.95,
      lat: 37.7852,
      lng: -122.4145,
      city: "sf",
    },
    {
      name: "Saturday jazz at Black Cat",
      venueName: "Black Cat",
      neighborhood: "Tenderloin",
      address: "400 Eddy St, San Francisco, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Ticketed · dinner optional",
      comedySubtype: "music.jazz",
      sourceUrl: "https://blackcatsf.com/",
      trustWeight: 0.95,
      lat: 37.7852,
      lng: -122.4145,
      city: "sf",
    },
    {
      name: "Live music at Sheba Piano Lounge",
      venueName: "Sheba Piano Lounge",
      neighborhood: "Fillmore",
      address: "1419 Fillmore St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 19,
      minute: 30,
      priceHint: "No cover · Ethiopian kitchen",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.shebapianolounge.com/",
      trustWeight: 0.9,
      lat: 37.7827,
      lng: -122.4327,
      city: "sf",
    },
    {
      name: "Sunday jazz at Sheba Piano Lounge",
      venueName: "Sheba Piano Lounge",
      neighborhood: "Fillmore",
      address: "1419 Fillmore St, San Francisco, CA",
      weekday: 0,
      nthWeekday: null,
      hour: 19,
      minute: 30,
      priceHint: "No cover · Ethiopian kitchen",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.shebapianolounge.com/",
      trustWeight: 0.85,
      lat: 37.7827,
      lng: -122.4327,
      city: "sf",
    },
    {
      name: "Fog City Swing at The Dawn Club",
      venueName: "The Dawn Club",
      neighborhood: "Financial District",
      address: "10 Annie St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Cover · swing / jazz",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.dawnclub.com/music",
      trustWeight: 0.9,
      lat: 37.7884,
      lng: -122.4017,
      city: "sf",
    },
    {
      name: "Live jazz at Keys Jazz Bistro",
      venueName: "Keys Jazz Bistro",
      neighborhood: "North Beach",
      address: "498 Broadway, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Cover · dinner",
      comedySubtype: "music.jazz",
      sourceUrl: "https://keysjazzbistro.com/",
      trustWeight: 0.9,
      lat: 37.798,
      lng: -122.4053,
      city: "sf",
    },
    {
      name: "Saturday jazz at Keys Jazz Bistro",
      venueName: "Keys Jazz Bistro",
      neighborhood: "North Beach",
      address: "498 Broadway, San Francisco, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Cover · dinner",
      comedySubtype: "music.jazz",
      sourceUrl: "https://keysjazzbistro.com/",
      trustWeight: 0.9,
      lat: 37.798,
      lng: -122.4053,
      city: "sf",
    },
    {
      name: "Friday jazz at Bird & Beckett",
      venueName: "Bird & Beckett Books & Records",
      neighborhood: "Glen Park",
      address: "653 Chenery St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 19,
      minute: 30,
      priceHint: "Donation · bookstore",
      comedySubtype: "music.jazz",
      sourceUrl: "https://birdbeckett.com/",
      trustWeight: 0.9,
      lat: 37.7342,
      lng: -122.4342,
      city: "sf",
    },
    {
      name: "Organ jazz at Royal Cuckoo",
      venueName: "The Royal Cuckoo Organ Lounge",
      neighborhood: "Mission",
      address: "3201 Mission St, San Francisco, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "No cover · Hammond B-3",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.royalcuckoo.com/",
      trustWeight: 0.85,
      lat: 37.7525,
      lng: -122.4186,
      city: "sf",
    },
    {
      name: "Piano lounge jazz at Harris'",
      venueName: "Harris' Restaurant",
      neighborhood: "Pacific Heights",
      address: "2100 Van Ness Ave, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 19,
      minute: 0,
      priceHint: "No cover · cocktails",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.harrisrestaurant.com/bar-piano-lounge",
      trustWeight: 0.85,
      lat: 37.7878,
      lng: -122.4219,
      city: "sf",
    },
    {
      name: "Thursday trio at Harris'",
      venueName: "Harris' Restaurant",
      neighborhood: "Pacific Heights",
      address: "2100 Van Ness Ave, San Francisco, CA",
      weekday: 4,
      nthWeekday: null,
      hour: 18,
      minute: 30,
      priceHint: "No cover · cocktails",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.harrisrestaurant.com/bar-piano-lounge",
      trustWeight: 0.8,
      lat: 37.7878,
      lng: -122.4219,
      city: "sf",
    },
  ];

  /** Punk / indie / bar rooms — weekly hangouts, not arena tours. */
  const liveMusicBarSeed: RecurringSeedRow[] = [
    {
      name: "Live punk at Kilowatt",
      venueName: "Kilowatt",
      neighborhood: "Mission",
      address: "3160 16th St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover varies · punk / garage",
      comedySubtype: "music.punk",
      sourceUrl: "https://kilowattbar.com/events",
      trustWeight: 0.9,
      lat: 37.7651,
      lng: -122.4233,
      city: "sf",
    },
    {
      name: "Saturday punk at Kilowatt",
      venueName: "Kilowatt",
      neighborhood: "Mission",
      address: "3160 16th St, San Francisco, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover varies · punk / garage",
      comedySubtype: "music.punk",
      sourceUrl: "https://kilowattbar.com/events",
      trustWeight: 0.9,
      lat: 37.7651,
      lng: -122.4233,
      city: "sf",
    },
    {
      name: "Live music at The Knockout",
      venueName: "The Knockout",
      neighborhood: "Mission",
      address: "3223 Mission St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover varies · punk / rock",
      comedySubtype: "music.punk",
      sourceUrl: "https://theknockoutsf.com/",
      trustWeight: 0.9,
      lat: 37.7458,
      lng: -122.4195,
      city: "sf",
    },
    {
      name: "Reggae Sunday at The Knockout",
      venueName: "The Knockout",
      neighborhood: "Mission",
      address: "3223 Mission St, San Francisco, CA",
      weekday: 0,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover varies · reggae",
      comedySubtype: "music.live",
      sourceUrl: "https://theknockoutsf.com/",
      trustWeight: 0.85,
      lat: 37.7458,
      lng: -122.4195,
      city: "sf",
    },
    {
      name: "Indie / punk at Bottom of the Hill",
      venueName: "Bottom of the Hill",
      neighborhood: "Potrero Hill",
      address: "1233 17th St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 30,
      priceHint: "Ticketed · all ages often",
      comedySubtype: "music.punk",
      sourceUrl: "https://bottomofthehill.com/calendar.html",
      trustWeight: 0.95,
      lat: 37.7651,
      lng: -122.3972,
      city: "sf",
    },
    {
      name: "Saturday at Bottom of the Hill",
      venueName: "Bottom of the Hill",
      neighborhood: "Potrero Hill",
      address: "1233 17th St, San Francisco, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 20,
      minute: 30,
      priceHint: "Ticketed · all ages often",
      comedySubtype: "music.rock",
      sourceUrl: "https://bottomofthehill.com/calendar.html",
      trustWeight: 0.95,
      lat: 37.7651,
      lng: -122.3972,
      city: "sf",
    },
    {
      name: "Live music at Boom Boom Room",
      venueName: "Boom Boom Room",
      neighborhood: "Fillmore",
      address: "1601 Fillmore St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover · funk / blues / soul",
      comedySubtype: "music.blues",
      sourceUrl: "https://www.boomboomroom.com/",
      trustWeight: 0.9,
      lat: 37.7842,
      lng: -122.4333,
      city: "sf",
    },
    {
      name: "Live music at Rickshaw Stop",
      venueName: "Rickshaw Stop",
      neighborhood: "Hayes Valley",
      address: "155 Fell St, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Ticketed · indie / dance",
      comedySubtype: "music.live",
      sourceUrl: "https://www.rickshawstop.com/",
      trustWeight: 0.9,
      lat: 37.7761,
      lng: -122.4205,
      city: "sf",
    },
    {
      name: "Punk / rock at Mabuhay Gardens",
      venueName: "Mabuhay Gardens",
      neighborhood: "North Beach",
      address: "443 Broadway, San Francisco, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Cover varies · punk legacy room",
      comedySubtype: "music.punk",
      sourceUrl: "https://themab.org/",
      trustWeight: 0.85,
      lat: 37.7979,
      lng: -122.4055,
      city: "sf",
    },
    // —— Chicago jazz / live rooms ——
    {
      name: "Live jazz at the Green Mill",
      venueName: "Green Mill Cocktail Lounge",
      neighborhood: "Uptown",
      address: "4802 N Broadway, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Cover · historic jazz",
      comedySubtype: "music.jazz",
      sourceUrl: "https://greenmilljazz.com/",
      trustWeight: 0.95,
      lat: 41.9692,
      lng: -87.6598,
      city: "chicago",
    },
    {
      name: "Saturday jazz at the Green Mill",
      venueName: "Green Mill Cocktail Lounge",
      neighborhood: "Uptown",
      address: "4802 N Broadway, Chicago, IL",
      weekday: 6,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Cover · historic jazz",
      comedySubtype: "music.jazz",
      sourceUrl: "https://greenmilljazz.com/",
      trustWeight: 0.95,
      lat: 41.9692,
      lng: -87.6598,
      city: "chicago",
    },
    {
      name: "Jazz Showcase",
      venueName: "Jazz Showcase",
      neighborhood: "South Loop",
      address: "806 S Plymouth Ct, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Ticketed · classic jazz",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.jazzshowcase.com/",
      trustWeight: 0.9,
      lat: 41.8715,
      lng: -87.628,
      city: "chicago",
    },
    {
      name: "Andy's Jazz Club",
      venueName: "Andy's Jazz Club",
      neighborhood: "River North",
      address: "11 E Hubbard St, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Cover · dinner jazz",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.andysjazzclub.com/",
      trustWeight: 0.9,
      lat: 41.8899,
      lng: -87.6276,
      city: "chicago",
    },
    {
      name: "Indie / punk at Empty Bottle",
      venueName: "Empty Bottle",
      neighborhood: "Ukrainian Village",
      address: "1035 N Western Ave, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover · indie / punk",
      comedySubtype: "music.punk",
      sourceUrl: "https://www.emptybottle.com/",
      trustWeight: 0.95,
      lat: 41.9005,
      lng: -87.6865,
      city: "chicago",
    },
    {
      name: "Saturday at Empty Bottle",
      venueName: "Empty Bottle",
      neighborhood: "Ukrainian Village",
      address: "1035 N Western Ave, Chicago, IL",
      weekday: 6,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover · indie / punk",
      comedySubtype: "music.rock",
      sourceUrl: "https://www.emptybottle.com/",
      trustWeight: 0.95,
      lat: 41.9005,
      lng: -87.6865,
      city: "chicago",
    },
    {
      name: "Blues at Kingston Mines",
      venueName: "Kingston Mines",
      neighborhood: "Lincoln Park",
      address: "2548 N Halsted St, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 30,
      priceHint: "Cover · late blues",
      comedySubtype: "music.blues",
      sourceUrl: "https://www.kingstonmines.com/",
      trustWeight: 0.9,
      lat: 41.9295,
      lng: -87.649,
      city: "chicago",
    },
    {
      name: "Blues at Buddy Guy's Legends",
      venueName: "Buddy Guy's Legends",
      neighborhood: "South Loop",
      address: "700 S Wabash Ave, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover · blues institution",
      comedySubtype: "music.blues",
      sourceUrl: "https://buddyguy.com/",
      trustWeight: 0.9,
      lat: 41.8732,
      lng: -87.6259,
      city: "chicago",
    },
    {
      name: "Live music at Beat Kitchen",
      venueName: "Beat Kitchen",
      neighborhood: "Roscoe Village",
      address: "2100 W Belmont Ave, Chicago, IL",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover · rock / indie",
      comedySubtype: "music.rock",
      sourceUrl: "https://www.beatkitchen.com/",
      trustWeight: 0.85,
      lat: 41.9397,
      lng: -87.6805,
      city: "chicago",
    },
    // —— LA jazz / live rooms ——
    {
      name: "Jazz at Catalina Jazz Club",
      venueName: "Catalina Jazz Club",
      neighborhood: "Hollywood",
      address: "6725 W Sunset Blvd, Los Angeles, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Ticketed · supper club",
      comedySubtype: "music.jazz",
      sourceUrl: "https://catalinajazzclub.com/",
      trustWeight: 0.95,
      lat: 34.0978,
      lng: -118.3372,
      city: "la",
    },
    {
      name: "Saturday jazz at Catalina",
      venueName: "Catalina Jazz Club",
      neighborhood: "Hollywood",
      address: "6725 W Sunset Blvd, Los Angeles, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Ticketed · supper club",
      comedySubtype: "music.jazz",
      sourceUrl: "https://catalinajazzclub.com/",
      trustWeight: 0.95,
      lat: 34.0978,
      lng: -118.3372,
      city: "la",
    },
    {
      name: "Jazz at The Baked Potato",
      venueName: "The Baked Potato",
      neighborhood: "Studio City",
      address: "3787 Cahuenga Blvd, Studio City, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Cover · fusion jazz",
      comedySubtype: "music.jazz",
      sourceUrl: "https://www.thebakedpotato.com/",
      trustWeight: 0.9,
      lat: 34.1365,
      lng: -118.3618,
      city: "la",
    },
    {
      name: "Live music at Zebulon",
      venueName: "Zebulon",
      neighborhood: "Frogtown",
      address: "2478 Fletcher Dr, Los Angeles, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Ticketed · indie / experimental",
      comedySubtype: "music.live",
      sourceUrl: "https://zebulon.la/",
      trustWeight: 0.95,
      lat: 34.1065,
      lng: -118.2445,
      city: "la",
    },
    {
      name: "Saturday at Zebulon",
      venueName: "Zebulon",
      neighborhood: "Frogtown",
      address: "2478 Fletcher Dr, Los Angeles, CA",
      weekday: 6,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Ticketed · indie / experimental",
      comedySubtype: "music.live",
      sourceUrl: "https://zebulon.la/",
      trustWeight: 0.95,
      lat: 34.1065,
      lng: -118.2445,
      city: "la",
    },
    {
      name: "Live music at Lodge Room",
      venueName: "Lodge Room",
      neighborhood: "Highland Park",
      address: "104 N Avenue 56, Los Angeles, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 30,
      priceHint: "Ticketed · indie / rock",
      comedySubtype: "music.rock",
      sourceUrl: "https://www.lodgeroomhlp.com/",
      trustWeight: 0.9,
      lat: 34.1115,
      lng: -118.1935,
      city: "la",
    },
    {
      name: "Live music at The Troubadour",
      venueName: "Troubadour",
      neighborhood: "West Hollywood",
      address: "9081 Santa Monica Blvd, West Hollywood, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Ticketed · legendary rock club",
      comedySubtype: "music.rock",
      sourceUrl: "https://troubadour.com/",
      trustWeight: 0.9,
      lat: 34.0814,
      lng: -118.3894,
      city: "la",
    },
    {
      name: "Punk / indie at The Smell",
      venueName: "The Smell",
      neighborhood: "Downtown",
      address: "247 S Main St, Los Angeles, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 21,
      minute: 0,
      priceHint: "Donation · all-ages DIY",
      comedySubtype: "music.punk",
      sourceUrl: "https://smell.la/",
      trustWeight: 0.85,
      lat: 34.0505,
      lng: -118.2465,
      city: "la",
    },
    {
      name: "Live music at Whisky a Go Go",
      venueName: "Whisky a Go Go",
      neighborhood: "West Hollywood",
      address: "8901 Sunset Blvd, West Hollywood, CA",
      weekday: 5,
      nthWeekday: null,
      hour: 20,
      minute: 0,
      priceHint: "Ticketed · rock / punk",
      comedySubtype: "music.rock",
      sourceUrl: "https://whiskyagogo.com/",
      trustWeight: 0.85,
      lat: 34.0908,
      lng: -118.3856,
      city: "la",
    },
  ];

  for (const show of [...comedySeed, ...jazzSeed, ...liveMusicBarSeed]) {
    const existing = await db
      .select()
      .from(recurringShows)
      .where(
        and(
          eq(recurringShows.name, show.name),
          eq(recurringShows.city, show.city),
        ),
      )
      .limit(1);
    if (existing.length === 0) {
      await db.insert(recurringShows).values(show);
    } else {
      await db
        .update(recurringShows)
        .set({
          venueName: show.venueName,
          neighborhood: show.neighborhood,
          address: show.address,
          weekday: show.weekday,
          nthWeekday: show.nthWeekday,
          hour: show.hour,
          minute: show.minute,
          priceHint: show.priceHint,
          comedySubtype: show.comedySubtype,
          sourceUrl: show.sourceUrl,
          trustWeight: show.trustWeight,
          lat: show.lat,
          lng: show.lng,
        })
        .where(eq(recurringShows.id, existing[0]!.id));
    }
  }

  console.log("Seed complete. Demo user:", DEMO_USER_ID);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
