/**
 * Curated evergreen activities per metro — parks, hikes, local gems.
 * Ingest materializes one stable feed row per entry (see `activities` adapter).
 */

import type { CuratedActivity } from "./activityTips.js";

export type { CuratedActivity, ActivityAudience, ActivityKind } from "./activityTips.js";

/** SF / Bay — iconic highlights + local gems (~40% local_gem) */
export const CURATED_ACTIVITIES_SF: CuratedActivity[] = [
  // — Iconic / visitor —
  {
    id: "sf-ggp-walk",
    city: "sf",
    title: "Walk Golden Gate Park end to end",
    description:
      "Start at Stanyan and Fulton and walk west through meadows, lakes, and the botanical garden belt to Ocean Beach. Best on a weekday morning before the JFK promenade crowds.",
    venueName: "Golden Gate Park",
    neighborhood: "Richmond",
    lat: 37.7694,
    lng: -122.4862,
    url: "https://goldengatepark.com/",
    audience: "iconic",
    activityKind: "walk",
    tags: ["golden_gate_park", "walking"],
  },
  {
    id: "sf-dolores-park",
    city: "sf",
    title: "Hang at Dolores Park",
    description:
      "The classic sunny-afternoon spot — grab tacos on 18th, claim a slope with a view of downtown, and people-watch. Weekends get packed; weekday late afternoons are calmer.",
    venueName: "Dolores Park",
    neighborhood: "Mission",
    address: "Dolores St & 19th St, San Francisco",
    lat: 37.7596,
    lng: -122.4269,
    url: "https://sfrecpark.org/Facilities/Facility/Details/Dolores-Park-21",
    audience: "iconic",
    activityKind: "park",
    tags: ["dolores", "sunshine"],
  },
  {
    id: "sf-crissy-field",
    city: "sf",
    title: "Crissy Field waterfront stroll",
    description:
      "Flat path from the Marina to the Golden Gate Bridge with bay and bridge views the whole way. Pair with coffee on Chestnut or a detour to the Warming Hut.",
    venueName: "Crissy Field",
    neighborhood: "Marina",
    lat: 37.8021,
    lng: -122.4488,
    url: "https://www.parksconservancy.org/parks/crissy-field",
    audience: "iconic",
    activityKind: "walk",
    tags: ["waterfront", "bridge_views"],
  },
  {
    id: "sf-lands-end",
    city: "sf",
    title: "Lands End coastal trail",
    description:
      "Windy cliffside loop with Sutro baths ruins, cypress tunnels, and Pacific views. Connect to the Legion of Honor or Sutro Heights for a longer afternoon.",
    venueName: "Lands End",
    neighborhood: "Richmond",
    lat: 37.7879,
    lng: -122.4995,
    url: "https://www.parksconservancy.org/parks/lands-end",
    audience: "iconic",
    activityKind: "hike",
    tags: ["coastal", "trails"],
  },
  {
    id: "sf-ferry-embarcadero",
    city: "sf",
    title: "Ferry Building to Pier 7 waterfront walk",
    description:
      "Farmer's market mornings at the Ferry Building, then stroll the Embarcadero past cupolas and piers. End at Pier 7 for classic bay photos.",
    venueName: "Ferry Building",
    neighborhood: "Embarcadero",
    address: "1 Ferry Building, San Francisco",
    lat: 37.7956,
    lng: -122.3933,
    url: "https://www.ferrybuildingmarketplace.com/",
    audience: "iconic",
    activityKind: "walk",
    tags: ["waterfront", "market"],
  },
  {
    id: "sf-alamo-square",
    city: "sf",
    title: "Alamo Square & Painted Ladies",
    description:
      "Postcard view of the Painted Ladies with downtown behind them. Short loop around the hill; combine with Fillmore shopping or a Haight thrift run.",
    venueName: "Alamo Square",
    neighborhood: "Alamo Square",
    lat: 37.7766,
    lng: -122.433,
    url: "https://sfrecpark.org/Facilities/Facility/Details/Alamo-Square-25",
    audience: "iconic",
    activityKind: "viewpoint",
    tags: ["painted_ladies", "views"],
  },
  {
    id: "sf-twin-peaks",
    city: "sf",
    title: "Twin Peaks summit",
    description:
      "360° city views in fifteen minutes from the parking lot, or longer if you hike the surrounding trails. Bring a layer — it's often windy and foggy.",
    venueName: "Twin Peaks",
    neighborhood: "Twin Peaks",
    lat: 37.7544,
    lng: -122.4477,
    url: "https://sfrecpark.org/Facilities/Facility/Details/Twin-Peaks-40",
    audience: "iconic",
    activityKind: "viewpoint",
    tags: ["views", "sunset"],
  },

  // — Local gems —
  {
    id: "sf-emporium",
    city: "sf",
    title: "Emporium Arcade Bar",
    description:
      "Classic arcade cabinets, pinball, and cocktails in a cavernous SoMa space. Good for groups — buy a game card and rotate between cabinets and the bar.",
    venueName: "Emporium Arcade Bar",
    neighborhood: "SoMa",
    address: "616 Divisadero St, San Francisco",
    lat: 37.7765,
    lng: -122.4376,
    url: "https://www.emporiumsf.com/",
    audience: "local_gem",
    activityKind: "play",
    categories: ["nightlife", "arts"],
    tags: ["arcade_bar", "play_kind:arcade_bar"],
    isFree: false,
  },
  {
    id: "sf-detour",
    city: "sf",
    title: "Detour Bar",
    description:
      "Neighborhood arcade bar on Irving — skee-ball, retro games, and a low-key local crowd. Easy to miss if you don't know it's there.",
    venueName: "Detour Bar",
    neighborhood: "Inner Sunset",
    address: "2209 Irving St, San Francisco",
    lat: 37.7637,
    lng: -122.4818,
    url: "https://www.detourbarsf.com/",
    audience: "local_gem",
    activityKind: "play",
    categories: ["nightlife", "arts"],
    tags: ["arcade_bar", "play_kind:arcade_bar"],
    isFree: false,
  },
  {
    id: "sf-wasteland",
    city: "sf",
    title: "Wasteland vintage (Haight)",
    description:
      "Well-curated vintage clothing — the kind of thrift run locals do when they want a real score, not fast fashion castoffs. Budget an hour to dig.",
    venueName: "Wasteland",
    neighborhood: "Haight",
    address: "1660 Haight St, San Francisco",
    lat: 37.7699,
    lng: -122.4507,
    url: "https://www.shopwasteland.com/",
    audience: "local_gem",
    activityKind: "shop",
    tags: ["thrift", "vintage"],
    isFree: true,
  },
  {
    id: "sf-community-thrift",
    city: "sf",
    title: "Community Thrift",
    description:
      "Huge nonprofit thrift floor in the Mission — furniture, clothes, and oddities. Proceeds support local charities; prices beat most boutique vintage.",
    venueName: "Community Thrift",
    neighborhood: "Mission",
    address: "623 Valencia St, San Francisco",
    lat: 37.7627,
    lng: -122.4216,
    url: "https://www.communitythrift.org/",
    audience: "local_gem",
    activityKind: "shop",
    tags: ["thrift"],
    isFree: true,
  },
  {
    id: "sf-spark-social",
    city: "sf",
    title: "Spark Social SF",
    description:
      "Rotating food trucks, picnic tables, and mini-golf in a SoMa yard — easy group hang that visitors rarely find. Check the truck lineup before you go.",
    venueName: "Spark Social SF",
    neighborhood: "SoMa",
    address: "601 Mission Bay Blvd N, San Francisco",
    lat: 37.7715,
    lng: -122.3918,
    url: "https://www.sparksocialsf.com/",
    audience: "local_gem",
    activityKind: "food_yard",
    tags: ["food_trucks", "mini_golf", "play_kind:mini_golf"],
    isFree: false,
  },
  {
    id: "sf-presidio-range",
    city: "sf",
    title: "Presidio Golf Course driving range",
    description:
      "Bay-side buckets with bridge views — a surprisingly peaceful afternoon even if you're rusty. Rent clubs on site; no tee time needed for the range.",
    venueName: "Presidio Golf Course",
    neighborhood: "Presidio",
    address: "300 Finley Rd, San Francisco",
    lat: 37.7899,
    lng: -122.4598,
    url: "https://www.presidiogolf.com/driving-range/",
    audience: "local_gem",
    activityKind: "play",
    tags: ["driving_range", "play_kind:driving_range"],
    isFree: false,
  },
  {
    id: "sf-bad-axe",
    city: "sf",
    title: "Bad Axe Throwing (SoMa)",
    description:
      "Book a lane and throw axes with friends — staff coach beginners. More active than a bar night and a solid rainy-day option.",
    venueName: "Bad Axe Throwing",
    neighborhood: "SoMa",
    address: "920 Howard St, San Francisco",
    lat: 37.7819,
    lng: -122.4077,
    url: "https://badaxethrowing.com/san-francisco/",
    audience: "local_gem",
    activityKind: "play",
    tags: ["axe_throwing", "play_kind:axe_throwing"],
    isFree: false,
  },
  {
    id: "sf-clarion-alley",
    city: "sf",
    title: "Clarion Alley mural walk",
    description:
      "Dense, political, ever-changing murals in a single block off Mission — self-guided and free. Go slow; new pieces appear often.",
    venueName: "Clarion Alley",
    neighborhood: "Mission",
    lat: 37.7569,
    lng: -122.4195,
    url: "https://clarionalleymuralproject.org/",
    audience: "local_gem",
    activityKind: "murals",
    tags: ["street_art", "mission"],
  },
  {
    id: "sf-balmy-alley",
    city: "sf",
    title: "Balmy Alley murals",
    description:
      "Latin American mural tradition in the Mission — shorter than Clarion but deeply rooted. Pair with a burrito on 24th.",
    venueName: "Balmy Alley",
    neighborhood: "Mission",
    lat: 37.7518,
    lng: -122.4122,
    audience: "local_gem",
    activityKind: "murals",
    tags: ["street_art", "mission"],
  },
  {
    id: "sf-mission-mural-route",
    city: "sf",
    title: "24th St mural route",
    description:
      "Walk 24th from Potrero to Bryant — murals on shutters, walls, and schoolyards. Best in daylight; many spots are easy to miss from a car.",
    venueName: "24th Street corridor",
    neighborhood: "Mission",
    lat: 37.7523,
    lng: -122.4145,
    audience: "local_gem",
    activityKind: "walk",
    categories: ["arts", "outdoors", "free"],
    tags: ["street_art", "mission", "murals"],
  },
  {
    id: "sf-bernal-heights",
    city: "sf",
    title: "Bernal Heights Park loop",
    description:
      "Locals' favorite hill — short climb, big views, off-leash dogs, and a quiet loop at the top. Sunset spot that tourists rarely hit.",
    venueName: "Bernal Heights Park",
    neighborhood: "Bernal Heights",
    lat: 37.743,
    lng: -122.4158,
    url: "https://sfrecpark.org/Facilities/Facility/Details/Bernal-Heights-Park-34",
    audience: "local_gem",
    activityKind: "hike",
    tags: ["views", "dog_friendly"],
  },
  {
    id: "sf-mount-sutro",
    city: "sf",
    title: "Mount Sutro forest loop",
    description:
      "Foggy eucalyptus forest in the middle of the city — feels like a NorCal trail without leaving SF. Muddy after rain; wear real shoes.",
    venueName: "Mount Sutro Open Space",
    neighborhood: "Inner Sunset",
    lat: 37.7592,
    lng: -122.4571,
    url: "https://www.sutrostewards.org/",
    audience: "local_gem",
    activityKind: "hike",
    tags: ["forest", "trails"],
  },
  {
    id: "sf-glen-canyon",
    city: "sf",
    title: "Glen Canyon Park",
    description:
      "Sandstone cliffs and a creek trail hidden between Noe Valley and Glen Park — easy to overlook if you stick to the flat neighborhoods.",
    venueName: "Glen Canyon Park",
    neighborhood: "Glen Park",
    lat: 37.7411,
    lng: -122.4334,
    url: "https://sfrecpark.org/Facilities/Facility/Details/Glen-Canyon-Park-29",
    audience: "local_gem",
    activityKind: "park",
    tags: ["trails", "hidden_gem"],
  },
  {
    id: "sf-seward-slides",
    city: "sf",
    title: "Seward Mini Park slides",
    description:
      "Concrete slides built into a hillside in the Castro — bring cardboard. Weird, very SF, and most adults haven't been since they were kids.",
    venueName: "Seward Mini Park",
    neighborhood: "Castro",
    address: "Seward St & Douglass St, San Francisco",
    lat: 37.7572,
    lng: -122.4387,
    url: "https://sfrecpark.org/Facilities/Facility/Details/Seward-Mini-Park-373",
    audience: "local_gem",
    activityKind: "play",
    tags: ["slides", "play_kind:slides"],
    isFree: true,
  },
  {
    id: "sf-baker-beach-bluffs",
    city: "sf",
    title: "Baker Beach to Batteries to Bluffs",
    description:
      "Sand, bridge views, then a short bluff trail through the Presidio batteries. Combine with the Presidio range for a full afternoon.",
    venueName: "Baker Beach",
    neighborhood: "Presidio",
    lat: 37.7936,
    lng: -122.4838,
    url: "https://www.parksconservancy.org/parks/baker-beach",
    audience: "local_gem",
    activityKind: "walk",
    tags: ["beach", "presidio"],
  },
  {
    id: "sf-palace-fine-arts",
    city: "sf",
    title: "Palace of Fine Arts lagoon walk",
    description:
      "Rotunda and reflecting pool in the Marina — short loop, great photos, and calm even when the rest of the city is loud. Free to wander the grounds.",
    venueName: "Palace of Fine Arts",
    neighborhood: "Marina",
    address: "3601 Lyon St, San Francisco",
    lat: 37.8029,
    lng: -122.4486,
    url: "https://www.palaceoffinearts.org/",
    audience: "iconic",
    activityKind: "viewpoint",
    tags: ["marina", "architecture"],
  },
  {
    id: "sf-gg-bridge-walk",
    city: "sf",
    title: "Golden Gate Bridge east sidewalk",
    description:
      "Walk the bridge deck to the first tower and back — wind, views, and bragging rights. Weekday mornings beat weekend crowds; dress warm.",
    venueName: "Golden Gate Bridge",
    neighborhood: "Presidio",
    lat: 37.8078,
    lng: -122.475,
    url: "https://www.goldengate.org/bridge/visiting-the-bridge/",
    audience: "iconic",
    activityKind: "walk",
    tags: ["bridge", "views"],
  },
  {
    id: "sf-stow-lake",
    city: "sf",
    title: "Stow Lake loop (Golden Gate Park)",
    description:
      "Flat mile around the lake with Strawberry Hill in the middle — rent a paddle boat in season or walk the full loop in under an hour.",
    venueName: "Stow Lake",
    neighborhood: "Richmond",
    lat: 37.7691,
    lng: -122.4771,
    url: "https://goldengatepark.com/stow-lake-boathouse.html",
    audience: "iconic",
    activityKind: "park",
    tags: ["golden_gate_park", "boating"],
  },
  {
    id: "sf-botanical-garden",
    city: "sf",
    title: "San Francisco Botanical Garden",
    description:
      "55 acres of curated gardens in GG Park — cloud forest, succulents, and quiet paths. SF residents get free entry; tourists pay but it's worth a slow morning.",
    venueName: "San Francisco Botanical Garden",
    neighborhood: "Richmond",
    address: "1199 9th Ave, San Francisco",
    lat: 37.767,
    lng: -122.469,
    url: "https://www.sfbg.org/",
    audience: "iconic",
    activityKind: "park",
    tags: ["golden_gate_park", "gardens"],
  },
  {
    id: "sf-filbert-steps",
    city: "sf",
    title: "Filbert Street Steps to Coit Tower",
    description:
      "Wooden stairways through gardens on Telegraph Hill — the classic SF urban hike with bay views at the top. Continue to Coit if your calves allow.",
    venueName: "Filbert Street Steps",
    neighborhood: "North Beach",
    lat: 37.8016,
    lng: -122.4058,
    audience: "iconic",
    activityKind: "hike",
    tags: ["stairs", "views"],
  },
  {
    id: "sf-ocean-beach",
    city: "sf",
    title: "Ocean Beach walk",
    description:
      "Wide Pacific beach at the west end of the city — bonfire pits, sunset walks, and the Cliff House ruins nearby. Foggy and cold most days; bring a layer.",
    venueName: "Ocean Beach",
    neighborhood: "Sunset",
    lat: 37.7594,
    lng: -122.5107,
    url: "https://www.nps.gov/goga/planyourvisit/ocean-beach.htm",
    audience: "iconic",
    activityKind: "walk",
    tags: ["beach", "sunset"],
  },
  {
    id: "sf-lyon-steps",
    city: "sf",
    title: "Lyon Street Steps",
    description:
      "Presidio Heights staircase with a postcard view of the Palace of Fine Arts and the bay — quick stop locals use for photos without the tourist crush.",
    venueName: "Lyon Street Steps",
    neighborhood: "Pacific Heights",
    lat: 37.7922,
    lng: -122.4472,
    audience: "local_gem",
    activityKind: "viewpoint",
    tags: ["stairs", "views"],
  },
  {
    id: "sf-fort-point",
    city: "sf",
    title: "Fort Point under the Golden Gate",
    description:
      "Civil War brick fortress directly under the bridge — free entry, wild perspective on the span, and often empty on weekday afternoons.",
    venueName: "Fort Point National Historic Site",
    neighborhood: "Presidio",
    lat: 37.8068,
    lng: -122.477,
    url: "https://www.nps.gov/fopo/",
    audience: "local_gem",
    activityKind: "viewpoint",
    tags: ["presidio", "history"],
    isFree: true,
  },
  {
    id: "sf-japantown",
    city: "sf",
    title: "Japantown Peace Plaza",
    description:
      "Pagoda, mall arcades, and ramen within a few blocks — easy cultural stroll that visitors skip for the bigger landmarks. Check the Peace Plaza on a quiet afternoon.",
    venueName: "Japan Center Peace Plaza",
    neighborhood: "Japantown",
    lat: 37.7852,
    lng: -122.4298,
    url: "https://www.sfjapantown.org/",
    audience: "local_gem",
    activityKind: "walk",
    tags: ["neighborhood"],
  },
  {
    id: "sf-mission-bowling",
    city: "sf",
    title: "Mission Bowling Club",
    description:
      "Boutique lanes with cocktails in the Mission — book ahead on weekends. The kind of place locals bring out-of-town friends who think SF doesn't do fun.",
    venueName: "Mission Bowling Club",
    neighborhood: "Mission",
    address: "3176 17th St, San Francisco",
    lat: 37.764,
    lng: -122.4194,
    url: "https://www.missionbowling.com/",
    audience: "local_gem",
    activityKind: "play",
    tags: ["bowling", "play_kind:bowling"],
    isFree: false,
  },
  {
    id: "sf-movement-climbing",
    city: "sf",
    title: "Movement San Francisco (bouldering)",
    description:
      "Huge bouldering gym in the Mission — day passes, shoe rental, and a social scene if you want an active evening that isn't a bar.",
    venueName: "Movement San Francisco",
    neighborhood: "SoMa",
    address: "1000 16th St, San Francisco",
    lat: 37.7656,
    lng: -122.3994,
    url: "https://movementgyms.com/san-francisco/",
    audience: "local_gem",
    activityKind: "play",
    tags: ["climbing", "play_kind:climbing"],
    isFree: false,
  },
  {
    id: "sf-angel-island",
    city: "sf",
    title: "Angel Island ferry day trip",
    description:
      "Ferry from the Ferry Building or Tiburon, then hike the perimeter trail for 360° bay views. Feels like a getaway; most weekender visitors never go.",
    venueName: "Angel Island State Park",
    neighborhood: "Embarcadero",
    lat: 37.861,
    lng: -122.4328,
    url: "https://www.parks.ca.gov/?page_id=468",
    audience: "local_gem",
    activityKind: "hike",
    tags: ["ferry", "island"],
    isFree: false,
  },
];

/** Chicago — iconic highlights + local gems */
export const CURATED_ACTIVITIES_CHI: CuratedActivity[] = [
  // — Iconic / visitor —
  {
    id: "chi-millennium-park",
    city: "chicago",
    title: "Millennium Park & Cloud Gate",
    description:
      "The Bean, Crown Fountain, and the Jay Pritzker Pavilion — start here for a classic Chicago afternoon. Weekday mornings are calmer; summer evenings bring free concerts on the lawn.",
    venueName: "Millennium Park",
    neighborhood: "The Loop",
    address: "201 E Randolph St, Chicago",
    lat: 41.8826,
    lng: -87.6226,
    url: "https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park.html",
    audience: "iconic",
    activityKind: "park",
    tags: ["cloud_gate", "the_bean"],
  },
  {
    id: "chi-lakefront-trail",
    city: "chicago",
    title: "Lakefront Trail ride or run",
    description:
      "18 miles of paved path along Lake Michigan — rent a Divvy for a short North Ave → Fullerton loop or run a flat out-and-back with skyline views the whole way.",
    venueName: "Lakefront Trail",
    neighborhood: "Lakeview",
    lat: 41.9214,
    lng: -87.6369,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/lakefront-trail",
    audience: "iconic",
    activityKind: "walk",
    tags: ["lakefront", "biking"],
  },
  {
    id: "chi-lincoln-park",
    city: "chicago",
    title: "Lincoln Park & zoo grounds walk",
    description:
      "Free zoo, lily pond, and miles of green space north of the Gold Coast — stroll the paths without a ticketed agenda. Pair with coffee on Armitage or a North Pond picnic.",
    venueName: "Lincoln Park",
    neighborhood: "Lincoln Park",
    lat: 41.9214,
    lng: -87.6334,
    url: "https://www.lpzoo.org/",
    audience: "iconic",
    activityKind: "park",
    tags: ["zoo", "free"],
  },
  {
    id: "chi-the-606",
    city: "chicago",
    title: "The 606 / Bloomingdale Trail",
    description:
      "Elevated rail-trail through Bucktown, Wicker Park, and Humboldt Park — city views, murals, and a flat walk or bike that feels nothing like the Loop below.",
    venueName: "The 606",
    neighborhood: "Wicker Park",
    lat: 41.9073,
    lng: -87.6774,
    url: "https://www.chicago.gov/city/en/depts/dca/supp_info/the606.html",
    audience: "iconic",
    activityKind: "walk",
    tags: ["trail", "elevated"],
  },
  {
    id: "chi-riverwalk",
    city: "chicago",
    title: "Chicago Riverwalk stroll",
    description:
      "Walk the river from Wolf Point east — bridges, architecture, and summer bar pop-ups on the water. Best at golden hour when the towers light up.",
    venueName: "Chicago Riverwalk",
    neighborhood: "The Loop",
    lat: 41.8885,
    lng: -87.6225,
    url: "https://www.chicago.gov/city/en/depts/dca/supp_info/chicago_riverwalk.html",
    audience: "iconic",
    activityKind: "walk",
    tags: ["architecture", "waterfront"],
  },
  {
    id: "chi-navy-pier",
    city: "chicago",
    title: "Navy Pier boardwalk",
    description:
      "Touristy but worth it once — lake breezes, skyline views, and a long pier walk. Skip the carnival rides unless you're with kids; the east end is the payoff.",
    venueName: "Navy Pier",
    neighborhood: "Streeterville",
    address: "600 E Grand Ave, Chicago",
    lat: 41.8919,
    lng: -87.6086,
    url: "https://navypier.org/",
    audience: "iconic",
    activityKind: "walk",
    tags: ["lakefront", "views"],
  },
  {
    id: "chi-grant-park",
    city: "chicago",
    title: "Grant Park & Buckingham Fountain",
    description:
      "Chicago's front yard — fountain shows in season, wide lawns, and a straight shot to the lake. Easy add-on before or after the Art Institute.",
    venueName: "Grant Park",
    neighborhood: "The Loop",
    lat: 41.8758,
    lng: -87.6189,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/grant-park-buckingham-fountain/",
    audience: "iconic",
    activityKind: "viewpoint",
    tags: ["fountain", "skyline"],
  },

  // — Local gems —
  {
    id: "chi-puttery",
    city: "chicago",
    title: "Puttery (mini-golf near downtown)",
    description:
      "Upscale mini-golf and cocktails in Fulton Market — the kind of place Chicagoans are surprised exists this close to downtown. Book ahead on weekends.",
    venueName: "Puttery",
    neighborhood: "West Loop",
    address: "919 W Fulton Market, Chicago",
    lat: 41.8865,
    lng: -87.6512,
    url: "https://www.puttery.com/chicago/",
    audience: "local_gem",
    activityKind: "play",
    categories: ["nightlife", "family"],
    tags: ["mini_golf", "play_kind:mini_golf"],
    isFree: false,
  },
  {
    id: "chi-emporium",
    city: "chicago",
    title: "Emporium Arcade Bar (Wicker Park)",
    description:
      "Pinball, retro cabinets, and a late-night crowd on Milwaukee Ave — the Chicago outpost of the arcade-bar format. Good for a low-plan group night.",
    venueName: "Emporium Arcade Bar",
    neighborhood: "Wicker Park",
    address: "1366 N Milwaukee Ave, Chicago",
    lat: 41.9084,
    lng: -87.6746,
    url: "https://www.emporiumchicago.com/",
    audience: "local_gem",
    activityKind: "play",
    categories: ["nightlife", "arts"],
    tags: ["arcade_bar", "play_kind:arcade_bar"],
    isFree: false,
  },
  {
    id: "chi-replay",
    city: "chicago",
    title: "Replay Beer & Bourbon",
    description:
      "Andersonville arcade bar with classic games and a neighborhood feel — less scene-y than Wicker Park, easy to miss if you don't live up north.",
    venueName: "Replay Beer & Bourbon",
    neighborhood: "Andersonville",
    address: "5368 N Clark St, Chicago",
    lat: 41.9797,
    lng: -87.6685,
    url: "https://www.replaybarandlounge.com/",
    audience: "local_gem",
    activityKind: "play",
    categories: ["nightlife", "arts"],
    tags: ["arcade_bar", "play_kind:arcade_bar"],
    isFree: false,
  },
  {
    id: "chi-unique-thrift",
    city: "chicago",
    title: "Unique Thrift (Elston Ave)",
    description:
      "Big-floor Savers-family thrift with real turnover — vintage denim, coats, and oddities if you're willing to dig. Locals treat it like a sport, not a quick errand.",
    venueName: "Unique",
    neighborhood: "Avondale",
    address: "3748 N Elston Ave, Chicago",
    lat: 41.9495,
    lng: -87.7134,
    url: "https://stores.savers.com/il/chicago/unique-thrift-store-8007.html",
    audience: "local_gem",
    activityKind: "shop",
    tags: ["thrift", "vintage"],
    isFree: true,
  },
  {
    id: "chi-village-discount",
    city: "chicago",
    title: "Village Discount Outlet",
    description:
      "Deep-discount thrift chain Chicagoans swear by — hit the Rogers Park or Portage Park locations for the best racks. Prices beat most boutique vintage.",
    venueName: "Village Discount Outlet",
    neighborhood: "Rogers Park",
    address: "7555 N Western Ave, Chicago",
    lat: 42.0186,
    lng: -87.6908,
    url: "https://www.villagediscount.com/",
    audience: "local_gem",
    activityKind: "shop",
    tags: ["thrift"],
    isFree: true,
  },
  {
    id: "chi-politan-row",
    city: "chicago",
    title: "Politan Row food hall",
    description:
      "Rotating vendors under one roof in the Medical District — grab a table, split a few counters, and treat it like a casual tasting menu with friends.",
    venueName: "Politan Row",
    neighborhood: "Near West Side",
    address: "1111 W Polk St, Chicago",
    lat: 41.8716,
    lng: -87.6535,
    url: "https://politanrow.com/",
    audience: "local_gem",
    activityKind: "food_yard",
    tags: ["food_hall"],
    isFree: false,
  },
  {
    id: "chi-pilsen-16th-murals",
    city: "chicago",
    title: "16th Street Pilsen murals",
    description:
      "Block-long mural corridor on 16th between Halsted and Western — self-guided, always changing, and free. Go slow; many pieces tell neighborhood history.",
    venueName: "16th Street Murals",
    neighborhood: "Pilsen",
    lat: 41.8598,
    lng: -87.6567,
    url: "https://pilsenarts.org/",
    audience: "local_gem",
    activityKind: "murals",
    tags: ["street_art", "pilsen"],
  },
  {
    id: "chi-wabash-arts",
    city: "chicago",
    title: "Wabash Arts corridor",
    description:
      "Columbia College's open-air gallery — murals and installations along Wabash south of Roosevelt. Easy loop on foot before a South Loop dinner.",
    venueName: "Wabash Arts Corridor",
    neighborhood: "South Loop",
    lat: 41.8747,
    lng: -87.6262,
    url: "https://wabasharts.com/",
    audience: "local_gem",
    activityKind: "murals",
    tags: ["street_art", "campus"],
  },
  {
    id: "chi-pilsen-18th-walk",
    city: "chicago",
    title: "18th Street Pilsen walk",
    description:
      "Galleries, taquerias, and murals on 18th — the street locals use to show visitors 'real Pilsen.' Best on a Saturday afternoon before it gets loud.",
    venueName: "18th Street corridor",
    neighborhood: "Pilsen",
    lat: 41.8578,
    lng: -87.6694,
    audience: "local_gem",
    activityKind: "walk",
    categories: ["arts", "food", "outdoors", "free"],
    tags: ["pilsen", "murals"],
  },
  {
    id: "chi-diversey-range",
    city: "chicago",
    title: "Diversey Driving Range",
    description:
      "Lakefront buckets with skyline views — heated bays in winter, open air in summer. No tee time; show up and hit. Locals forget it's this close to the lake.",
    venueName: "Diversey Driving Range",
    neighborhood: "Lincoln Park",
    address: "301 W Diversey Pkwy, Chicago",
    lat: 41.9329,
    lng: -87.6366,
    url: "https://www.diversey-drivingrange.com/",
    audience: "local_gem",
    activityKind: "play",
    tags: ["driving_range", "play_kind:driving_range"],
    isFree: false,
  },
  {
    id: "chi-bad-axe",
    city: "chicago",
    title: "Bad Axe Throwing (West Loop)",
    description:
      "Book a lane and throw axes with friends — coaches walk beginners through it. Rainy-day energy that's more active than another brewery stop.",
    venueName: "Bad Axe Throwing",
    neighborhood: "West Loop",
    address: "165 N Loomis St, Chicago",
    lat: 41.8848,
    lng: -87.6389,
    url: "https://badaxethrowing.com/locations/axe-throwing-chicago-west-loop/",
    audience: "local_gem",
    activityKind: "play",
    tags: ["axe_throwing", "play_kind:axe_throwing"],
    isFree: false,
  },
  {
    id: "chi-ping-tom",
    city: "chicago",
    title: "Ping Tom Memorial Park",
    description:
      "Quiet riverfront park in Chinatown — pagoda, kayak launch, and a path most Loop workers never find. Great reset after dim sum on Wentworth.",
    venueName: "Ping Tom Memorial Park",
    neighborhood: "Chinatown",
    address: "1700 S Wentworth Ave, Chicago",
    lat: 41.8567,
    lng: -87.6336,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/ping-tom-memorial-park/",
    audience: "local_gem",
    activityKind: "park",
    tags: ["riverfront", "hidden_gem"],
  },
  {
    id: "chi-promontory-point",
    city: "chicago",
    title: "Promontory Point",
    description:
      "Stone peninsula in Hyde Park with wide lake views and a local swim/beach culture in summer. Feels like a neighborhood secret compared to North Ave.",
    venueName: "Promontory Point",
    neighborhood: "Hyde Park",
    lat: 41.7932,
    lng: -87.5782,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/promontory-point/",
    audience: "local_gem",
    activityKind: "park",
    tags: ["lakefront", "swim"],
  },
  {
    id: "chi-garfield-conservatory",
    city: "chicago",
    title: "Garfield Park Conservatory",
    description:
      "Massive free indoor gardens on the West Side — humid palm house in winter, fern room year-round. Locals go when they need green without leaving the city.",
    venueName: "Garfield Park Conservatory",
    neighborhood: "Garfield Park",
    address: "300 N Central Park Ave, Chicago",
    lat: 41.8864,
    lng: -87.7172,
    url: "https://garfieldconservatory.org/",
    audience: "local_gem",
    activityKind: "park",
    tags: ["conservatory", "free"],
    isFree: true,
  },
  {
    id: "chi-oz-park",
    city: "chicago",
    title: "Oz Park",
    description:
      "Wizard of Oz-themed neighborhood park in Lincoln Park — bronze characters, community garden vibes, and a low-key hang spot families actually use daily.",
    venueName: "Oz Park",
    neighborhood: "Lincoln Park",
    address: "2021 N Burling St, Chicago",
    lat: 41.9189,
    lng: -87.6468,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/oz-park/",
    audience: "local_gem",
    activityKind: "park",
    tags: ["neighborhood", "family"],
    isFree: true,
  },
  {
    id: "chi-montrose-bird-sanctuary",
    city: "chicago",
    title: "Montrose Bird Sanctuary & harbor",
    description:
      "Magic hedge migration spot and a quiet harbor loop — birders know it; most city dwellers don't. Early morning in spring is peak; still peaceful off-season.",
    venueName: "Montrose Point Bird Sanctuary",
    neighborhood: "Uptown",
    lat: 41.9678,
    lng: -87.6347,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/montrose-beach/",
    audience: "local_gem",
    activityKind: "hike",
    tags: ["birding", "lakefront"],
  },
  {
    id: "chi-maggie-daley",
    city: "chicago",
    title: "Maggie Daley Park",
    description:
      "Skating ribbon in winter, climbing walls and slides in summer — the loop's best all-ages playground. Connect to Millennium Park via the BP Bridge.",
    venueName: "Maggie Daley Park",
    neighborhood: "The Loop",
    address: "337 E Randolph St, Chicago",
    lat: 41.8822,
    lng: -87.6192,
    url: "https://maggiedaleypark.com/",
    audience: "iconic",
    activityKind: "park",
    tags: ["skating", "family"],
  },
  {
    id: "chi-cultural-center",
    city: "chicago",
    title: "Chicago Cultural Center",
    description:
      "Free Tiffany dome, rotating exhibits, and live music — the most beautiful public building downtown and most tourists walk past it.",
    venueName: "Chicago Cultural Center",
    neighborhood: "The Loop",
    address: "78 E Washington St, Chicago",
    lat: 41.8839,
    lng: -87.625,
    url: "https://www.chicago.gov/culturalcenter",
    audience: "iconic",
    activityKind: "viewpoint",
    categories: ["arts", "free"],
    tags: ["architecture", "free"],
    isFree: true,
  },
  {
    id: "chi-oak-street-beach",
    city: "chicago",
    title: "Oak Street Beach",
    description:
      "Sand and skyline together at the near north end of the lakefront — short walk from Michigan Ave. Packed on hot weekends; early morning is best.",
    venueName: "Oak Street Beach",
    neighborhood: "Gold Coast",
    lat: 41.9038,
    lng: -87.6236,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/oak-street-beach/",
    audience: "iconic",
    activityKind: "park",
    tags: ["beach", "lakefront"],
  },
  {
    id: "chi-northerly-island",
    city: "chicago",
    title: "Northerly Island trail",
    description:
      "Former airport peninsula turned park — flat loop with prairie plantings and unobstructed skyline views. Easy bike or walk from Museum Campus.",
    venueName: "Northerly Island",
    neighborhood: "South Loop",
    lat: 41.8612,
    lng: -87.6088,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/northerly-island/",
    audience: "local_gem",
    activityKind: "walk",
    tags: ["skyline", "lakefront"],
  },
  {
    id: "chi-humboldt-lagoon",
    city: "chicago",
    title: "Humboldt Park lagoon",
    description:
      "Boathouse, paddle boats in summer, and a Puerto Rican cultural corridor nearby — a west-side hang that downtown workers rarely see.",
    venueName: "Humboldt Park",
    neighborhood: "Humboldt Park",
    lat: 41.9054,
    lng: -87.7019,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/humboldt-park/",
    audience: "local_gem",
    activityKind: "park",
    tags: ["lagoon", "neighborhood"],
  },
  {
    id: "chi-lily-pool",
    city: "chicago",
    title: "Alfred Caldwell Lily Pool",
    description:
      "Hidden prairie-style garden in Lincoln Park — quiet paths, stone work, and birds. Easy to miss if you only do the zoo and lakefront.",
    venueName: "Alfred Caldwell Lily Pool",
    neighborhood: "Lincoln Park",
    lat: 41.9267,
    lng: -87.6347,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/alfred-caldwell-lily-pool/",
    audience: "local_gem",
    activityKind: "park",
    tags: ["garden", "quiet"],
    isFree: true,
  },
  {
    id: "chi-logan-arcade",
    city: "chicago",
    title: "Logan Arcade",
    description:
      "Two floors of pinball and arcade cabinets in Logan Square — BYO food from the neighborhood, stay for hours. Local default for rainy nights.",
    venueName: "Logan Arcade",
    neighborhood: "Logan Square",
    address: "2415 N Milwaukee Ave, Chicago",
    lat: 41.9258,
    lng: -87.7086,
    url: "https://www.loganarcade.com/",
    audience: "local_gem",
    activityKind: "play",
    categories: ["nightlife", "arts"],
    tags: ["arcade_bar", "play_kind:arcade_bar"],
    isFree: false,
  },
  {
    id: "chi-whirlyball",
    city: "chicago",
    title: "WhirlyBall",
    description:
      "Bumpers + lacrosse + electric carts in Lincoln Park — ridiculous group activity most Chicagoans forget exists until someone books a birthday.",
    venueName: "WhirlyBall Chicago",
    neighborhood: "Lincoln Park",
    address: "1880 W Webster Ave, Chicago",
    lat: 41.9214,
    lng: -87.6755,
    url: "https://www.whirlyball.com/chicago/",
    audience: "local_gem",
    activityKind: "play",
    tags: ["whirlyball", "play_kind:whirlyball"],
    isFree: false,
  },
  {
    id: "chi-chinatown-square",
    city: "chicago",
    title: "Chinatown Square stroll",
    description:
      "Zodiac sculptures, bakeries, and tea shops on Wentworth — self-guided loop before dim sum. Less polished than downtown but more neighborhood-real.",
    venueName: "Chinatown Square",
    neighborhood: "Chinatown",
    lat: 41.8506,
    lng: -87.6322,
    audience: "local_gem",
    activityKind: "walk",
    tags: ["chinatown", "food"],
  },
  {
    id: "chi-logan-boulevard",
    city: "chicago",
    title: "Logan Boulevard mansions walk",
    description:
      "Wide boulevard with greystone mansions and a community garden belt — flat stroll locals use on the way to Milwaukee Ave bars and restaurants.",
    venueName: "Logan Boulevard",
    neighborhood: "Logan Square",
    lat: 41.9284,
    lng: -87.697,
    audience: "local_gem",
    activityKind: "walk",
    tags: ["architecture", "neighborhood"],
  },
  {
    id: "chi-printers-row",
    city: "chicago",
    title: "Printer's Row book district",
    description:
      "Historic publishing blocks south of the Loop — used bookstores, Lit Fest in June, and a quieter alternative to Michigan Ave shopping.",
    venueName: "Printer's Row",
    neighborhood: "South Loop",
    lat: 41.8715,
    lng: -87.6285,
    url: "https://www.printersrowlitfest.org/",
    audience: "local_gem",
    activityKind: "shop",
    tags: ["books", "neighborhood"],
    isFree: true,
  },
  {
    id: "chi-north-ave-beach",
    city: "chicago",
    title: "North Avenue Beach",
    description:
      "Castillo-style beach house, volleyball, and the classic skyline-in-background photo. More local energy than Navy Pier with the same lake views.",
    venueName: "North Avenue Beach",
    neighborhood: "Lincoln Park",
    lat: 41.914,
    lng: -87.628,
    url: "https://www.chicagoparkdistrict.com/parks-facilities/north-avenue-beach/",
    audience: "local_gem",
    activityKind: "park",
    tags: ["beach", "lakefront"],
  },
];

/** All metros */
export const CURATED_ACTIVITIES: readonly CuratedActivity[] = [
  ...CURATED_ACTIVITIES_SF,
  ...CURATED_ACTIVITIES_CHI,
] as const;
